name: Collect
on:
  # executed once a week on Sundays at 00:00
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

env:
  # time zone
  TZ: Asia/Shanghai

  # github access token
  GIST_PAT: ${{ secrets.GIST_PAT }}

  # github username and gist id, separated by '/'
  GIST_LINK: ${{ secrets.GIST_LINK }}

  # oss access key id
  OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}

  # oss access key secret
  OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

  # oss bucket name
  OSS_BUCKET: ${{ secrets.OSS_BUCKET }}

  # oss endpoint
  OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}

  # oss path
  OSS_PATH: ${{ secrets.OSS_PATH }}

  # the url to the list of airports that you maintain yourself
  # each line include domain, coupon and invitation code, the domain must be included, and the latter two items are optional
  CUSTOMIZE_LINK: ${{ secrets.CUSTOMIZE_LINK }}

  # include special protocols, such as vless hysteria2 and hysteria
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Check
        run: |
          # 检查是否至少配置了 GIST 或 OSS 中的一个
          if [ -z "$GIST_PAT" ] && [ -z "$OSS_ACCESS_KEY_ID" ]; then
              echo "Error: At least one of GIST or OSS configuration must be provided"
              exit 1
          fi

          # 如果配置了 GIST,检查 GIST 配置的完整性
          if [ ! -z "$GIST_PAT" ]; then
              if [ -z "$GIST_LINK" ]; then
                  echo "Error: When using GIST, environment 'GIST_LINK' cannot be empty"
                  exit 1
              fi

              LINK_PARTS=$(echo "$GIST_LINK" | awk -F'/' 'NF==2 && $1!="" && $2!=""')
              if [ -z "$LINK_PARTS" ]; then
                  echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
                  exit 1
              fi
          fi

          # 如果配置了 OSS,检查 OSS 配置的完整性
          if [ ! -z "$OSS_ACCESS_KEY_ID" ]; then
              if [ -z "$OSS_ACCESS_KEY_SECRET" ] || [ -z "$OSS_BUCKET" ] || [ -z "$OSS_ENDPOINT" ]; then
                  echo "Error: When using OSS, all OSS-related configurations must be provided"
                  exit 1
              fi
          fi

      - name: Collect
        run: python -u subscribe/collect.py --all --overwrite --skip

      - name: Timestamp
        run: date
